import 'package:flutter/material.dart';

class IconUtils {
  static IconData getIconData(String iconName) {
    final iconMap = {
      // Common Icons
      "propane_tank_rounded" : Icons.propane_tank_rounded,
      "event_available" : Icons.event_available,
      "shopping_bag" : Icons.shopping_bag,
      "fastfood" : Icons.fastfood,
      "church" : Icons.church,
      "power": Icons.power,
      "flash_on": Icons.flash_on,
      'smartphone': Icons.smartphone,
      'home': Icons.home,
      'settings': Icons.settings,
      'person': Icons.person,
      'email': Icons.email,
      'phone': Icons.phone,
      'lock': Icons.lock,
      'search': Icons.search,
      'shopping_cart': Icons.shopping_cart,
      'payment': Icons.payment,
      'account_balance': Icons.account_balance,
      'credit_card': Icons.credit_card,
      'receipt': Icons.receipt,
      'attach_money': Icons.attach_money,
      'account_balance_wallet': Icons.account_balance_wallet,
      'notifications': Icons.notifications,
      'build': Icons.build,
      'help': Icons.help,
      'info': Icons.info,
      'warning': Icons.warning,
      'error': Icons.error,
      'check_circle': Icons.check_circle,
      'location_on': Icons.location_on,
      'calendar_today': Icons.calendar_today,
      'star': Icons.star,
      'favorite': Icons.favorite,
      'local_gas_station_sharp': Icons.local_gas_station_sharp,
      'electric_bolt_sharp': Icons.electric_bolt_sharp,

      // Financial Services
      'money': Icons.money,
      'currency_exchange': Icons.currency_exchange,
      'savings': Icons.savings,
      'price_check': Icons.price_check,
      'request_quote': Icons.request_quote,
      'trending_up': Icons.trending_up,
      'trending_down': Icons.trending_down,
      'pie_chart': Icons.pie_chart,
      'bar_chart': Icons.bar_chart,
      'analytics': Icons.analytics,

      // Communication & Social
      'message': Icons.message,
      'chat': Icons.chat,
      'call': Icons.call,
      'mail': Icons.mail,
      'video_call': Icons.video_call,
      'group': Icons.group,
      'share': Icons.share,
      'thumb_up': Icons.thumb_up,
      'comment': Icons.comment,
      'forum': Icons.forum,

      // Utilities & Settings
      'light': Icons.light,
      'water_drop': Icons.water_drop,
      'electric_bolt': Icons.electric_bolt,
      'wifi': Icons.wifi,
      'bluetooth': Icons.bluetooth,
      'battery_full': Icons.battery_full,
      'signal_cellular_alt': Icons.signal_cellular_alt,
      'thermostat': Icons.thermostat,
      'schedule': Icons.schedule,
      'timer': Icons.timer,

      // Transport & Travel
      'directions_car': Icons.directions_car,
      'local_taxi': Icons.local_taxi,
      'directions_bus': Icons.directions_bus,
      'two_wheeler': Icons.two_wheeler,
      'flight': Icons.flight,
      'train': Icons.train,
      'directions_boat': Icons.directions_boat,
      'local_shipping': Icons.local_shipping,
      'map': Icons.map,
      'directions': Icons.directions,
      ''

      // Education & Learning
      'school': Icons.school,
      'book': Icons.book,
      'library_books': Icons.library_books,
      'class_': Icons.class_,
      'assignment': Icons.assignment,
      'quiz': Icons.quiz,
      'science': Icons.science,
      'calculate': Icons.calculate,
      'psychology': Icons.psychology,
      'language': Icons.language,
      'directions_boat_outlined' : Icons.directions_boat_outlined,

      // Health & Medical
      'local_hospital': Icons.local_hospital,
      'medical_services': Icons.medical_services,
      'health_and_safety': Icons.health_and_safety,
      'medication': Icons.medication,
      'healing': Icons.healing,
      'monitor_heart': Icons.monitor_heart,
      'fitness_center': Icons.fitness_center,
      'spa': Icons.spa,
      'psychology_alt': Icons.psychology_alt,
      'vaccines': Icons.vaccines,
      'credit_score_outlined' : Icons.credit_score_outlined,
      'network_wifi' : Icons.network_wifi,

      // Business & Commerce
      'restaurant': Icons.restaurant,
      'local_grocery_store': Icons.local_grocery_store,
      'local_mall': Icons.local_mall,
      'hotel': Icons.hotel,
      'store': Icons.store,
      'inventory': Icons.inventory,
      'storefront': Icons.storefront,
      'work': Icons.work,
      'business_center': Icons.business_center,
      'factory': Icons.factory,
      'eau' : Icons.invert_colors_outlined,
      'theaters' : Icons.theaters,

      // Media & Entertainment
      'play_arrow': Icons.play_arrow,
      'pause': Icons.pause,
      'music_note': Icons.music_note,
      'movie': Icons.movie,
      'games': Icons.games,
      'photo_camera': Icons.photo_camera,
      'videocam': Icons.videocam,
      'headphones': Icons.headphones,
      'tv': Icons.tv,
      'theater_comedy': Icons.theater_comedy,

      // Weather & Nature
      'wb_sunny': Icons.wb_sunny,
      'cloud': Icons.cloud,
      'thunderstorm': Icons.thunderstorm,
      'ac_unit': Icons.ac_unit,
      'terrain': Icons.terrain,
      'park': Icons.park,
      'grass': Icons.grass,
      'pets': Icons.pets,
      'eco': Icons.eco,
      'landscape': Icons.landscape,

      // Files & Documents
      'file_copy': Icons.file_copy,
      'folder': Icons.folder,
      'cloud_upload': Icons.cloud_upload,
      'cloud_download': Icons.cloud_download,
      'attach_file': Icons.attach_file,
      'description': Icons.description,
      'picture_as_pdf': Icons.picture_as_pdf,
      'archive': Icons.archive,
      'delete': Icons.delete,
      'restore_from_trash': Icons.restore_from_trash,
    };
    return iconMap[iconName.toLowerCase()] ?? Icons.widgets;
  }
}